runtime: custom
env: flex

# Cloud Run configuration
automatic_scaling:
  min_num_instances: 0
  max_num_instances: 10

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

network:
  forwarded_ports:
    - 8080

env_variables:
  PORT: 8080