steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/streamlit-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'streamlit-app', 
         '--image=gcr.io/$PROJECT_ID/streamlit-app', 
         '--platform=managed', 
         '--region=us-central1',
         '--allow-unauthenticated']